spring.application.name=GitHubLesson

spring.datasource.url=jdbc:postgresql://localhost:5432/all_projects_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update